name: Feature
description: Introduce a new feature
labels: ["feature"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
