name: Refactor
description: Refactor code
labels: ["refactor"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: changes
    attributes:
      label: Changes
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
