export { default as bolt } from './bolt.svg'
export { default as favicon } from './favicon.svg'
export { default as image } from './image.svg'
export { default as imjiMark } from './imji-mark.svg'
export { default as upload } from './upload.svg'
