name: CI
on: push
permissions:
  security-events: write
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  codeql:
    needs: lint
    uses: ./.github/workflows/codeql.yml
  build:
    needs: codeql
    uses: ./.github/workflows/build.yml
