name: CI
on: push
permissions:
  security-events: write
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  build:
    uses: ./.github/workflows/build.yml
  codeql:
    uses: ./.github/workflows/codeql.yml
